### Site Settings ###
title               : Vincenzo Nardelli
description         : >-
                      Personal Website of Vincenzo Nardelli, Research Fellow in Statistics at Università Cattolica del Sacro Cuore in Rome.
baseurl             : "/vincnardelli"

### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/blog.html
  - pages/projects.html

### Author Info ###
author:
  name              : Vincenzo Nardelli
  #image             : https://i.imgur.com/uyDNQnn.jpg
 # behance           : your_username
# dribbble          : your_username
#  email             : username@domain.com
#  facebook          : your_username
  github            : vincnardelli
# gitlab            : your_username
# instagram         : your_username
# kaggle            : your_username
  linkedin          : vincnardelli
#  medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
 # twitter           : your_username
# vimeo             : your_username
# youtube           : your_channel_name


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name
  papers:
    output: true
    permalink: /papers/:name

### Disqus ###
disqus: your-short-name-disqus                          # Your website Shortname on disqus


### Analytics ###
analytics:
  enabled: false                                        # Set true to enable analytics
  google:
    tracking_id: your-google-tracking-id


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "papers"
    values:
      layout: "papers"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
